openapi: 3.0.0
info:
  title: MayaMaya
  description: ""
  version: 1.0.0
servers:
- url: https://api.mayamaya.us
  description: MayaMaya Web App Node API's
- url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
  description: MayaMaya Web App Realm API's
tags:
- name: MayaMaya App
paths:
  /addUser:
    post:
      tags:
      - MayaMaya App
      summary: Add a new user
      operationId: addUserPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addUser_body'
        required: true
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /update_registration_status/{id}:
    get:
      tags:
      - MayaMaya App
      summary: Update registration status
      operationId: update_registration_statusIdGET
      parameters:
      - name: id
        in: path
        description: ID of the registration
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /loginUser:
    post:
      tags:
      - MayaMaya App
      summary: Login user
      operationId: loginUserPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUser_body'
        required: true
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /loadUserProfile:
    get:
      tags:
      - MayaMaya App
      summary: Load user profile
      operationId: loadUserProfileGET
      parameters:
      - name: userId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /updateUserProfile:
    post:
      tags:
      - MayaMaya App
      summary: Update user profile
      operationId: updateUserProfilePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfileRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserProfileResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /getUserSprints:
    get:
      tags:
      - MayaMaya App
      summary: Get user sprints
      operationId: getUserSprintsGET
      parameters:
      - name: userId
        in: query
        description: User ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sprint'
                x-content-type: application/json
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /getQuizsBySprintId:
    post:
      tags:
      - MayaMaya App
      summary: Get quizzes by sprint ID
      operationId: getQuizsBySprintIdPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getQuizsBySprintId_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
                x-content-type: application/json
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /getQuestionsByQuizId:
    post:
      tags:
      - MayaMaya App
      summary: Get questions by quiz ID
      operationId: getQuestionsByQuizIdPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getQuestionsByQuizId_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
                x-content-type: application/json
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /updateQuestion:
    post:
      tags:
      - MayaMaya App
      summary: Update a question
      operationId: updateQuestionPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateQuestionRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateQuestionResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /getSprintResult:
    post:
      tags:
      - MayaMaya App
      summary: Get sprint results for a user
      operationId: getSprintResultPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getSprintResult_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/SprintResult'
                x-content-type: application/json
      security:
      - bearerAuth: []
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /getResultDetailsById:
    get:
      tags:
      - MayaMaya App
      summary: Get result details by ID
      operationId: getResultDetailsByIdGET
      parameters:
      - name: resultId
        in: query
        description: The ID of the result
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResultDetailsResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://data.mongodb-api.com/app/mayamaya-app-production-uqomm/endpoint/mayamaya
      x-swagger-router-controller: MayaMayaApp
  /users/get_skill_results_dates:
    get:
      tags:
      - MayaMaya App
      summary: Get skill results dates
      operationId: usersGet_skill_results_datesGET
      parameters:
      - name: userId
        in: query
        description: The ID of the user
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSkillResultsDatesResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
  /users/update_skill_result_view:
    post:
      tags:
      - MayaMaya App
      summary: Update skill result view
      operationId: usersUpdate_skill_result_viewPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSkillResultViewRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSkillResultViewResponse'
      security:
      - bearerAuth: []
      servers:
      - url: https://api.mayamaya.us
      x-swagger-router-controller: MayaMayaApp
components:
  schemas:
    UserDetailsResponse:
      type: object
      properties:
        lastResult:
          $ref: '#/components/schemas/UserDetailsResponse_lastResult'
        countOfResults:
          type: string
        numberOfCompletedSprints:
          type: string
        status:
          type: string
        userDetails:
          $ref: '#/components/schemas/UserDetails'
      example:
        lastResult:
          resultDateTime: 2000-01-23T04:56:07.000+00:00
          _id: _id
        numberOfCompletedSprints: numberOfCompletedSprints
        countOfResults: countOfResults
        userDetails:
          profileDetails:
            country: country
            userPhoto: http://example.com/aeiou
            ethnicity: ethnicity
            gender: gender
            language: language
            accountId: accountId
            orgCode:
            - code: code
              isPrimary: isPrimary
              organization: organization
            - code: code
              isPrimary: isPrimary
              organization: organization
            profileId: profileId
            specialConsiderations:
            - specialConsiderations
            - specialConsiderations
            name: name
            designation: designation
            userType: userType
            region: region
            department: department
            email: ""
            age: age
          accountDetails:
            deviceType: deviceType
            accountId: accountId
            visits: visits
            loginTime: 2000-01-23T04:56:07.000+00:00
            role: role
            subscribedPlanType: subscribedPlanType
            userBadgeType: userBadgeType
            userId: userId
            deviceId: deviceId
            miramiraCoins: miramiraCoins
        status: status
    UserDetails:
      type: object
      properties:
        accountDetails:
          $ref: '#/components/schemas/AccountDetails'
        profileDetails:
          $ref: '#/components/schemas/ProfileDetails'
      example:
        profileDetails:
          country: country
          userPhoto: http://example.com/aeiou
          ethnicity: ethnicity
          gender: gender
          language: language
          accountId: accountId
          orgCode:
          - code: code
            isPrimary: isPrimary
            organization: organization
          - code: code
            isPrimary: isPrimary
            organization: organization
          profileId: profileId
          specialConsiderations:
          - specialConsiderations
          - specialConsiderations
          name: name
          designation: designation
          userType: userType
          region: region
          department: department
          email: ""
          age: age
        accountDetails:
          deviceType: deviceType
          accountId: accountId
          visits: visits
          loginTime: 2000-01-23T04:56:07.000+00:00
          role: role
          subscribedPlanType: subscribedPlanType
          userBadgeType: userBadgeType
          userId: userId
          deviceId: deviceId
          miramiraCoins: miramiraCoins
    AccountDetails:
      type: object
      properties:
        accountId:
          type: string
        userId:
          type: string
        deviceType:
          type: string
        deviceId:
          type: string
        loginTime:
          type: string
          format: date-time
        role:
          type: string
        visits:
          type: string
        miramiraCoins:
          type: string
        userBadgeType:
          type: string
        subscribedPlanType:
          type: string
      example:
        deviceType: deviceType
        accountId: accountId
        visits: visits
        loginTime: 2000-01-23T04:56:07.000+00:00
        role: role
        subscribedPlanType: subscribedPlanType
        userBadgeType: userBadgeType
        userId: userId
        deviceId: deviceId
        miramiraCoins: miramiraCoins
    ProfileDetails:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        country:
          type: string
        region:
          type: string
        ethnicity:
          type: string
        age:
          type: string
        gender:
          type: string
        specialConsiderations:
          type: array
          items:
            type: string
        userPhoto:
          type: string
          format: uri
        orgCode:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationCode'
        department:
          type: string
        designation:
          type: string
        accountId:
          type: string
        language:
          type: string
        userType:
          type: string
        profileId:
          type: string
      example:
        country: country
        userPhoto: http://example.com/aeiou
        ethnicity: ethnicity
        gender: gender
        language: language
        accountId: accountId
        orgCode:
        - code: code
          isPrimary: isPrimary
          organization: organization
        - code: code
          isPrimary: isPrimary
          organization: organization
        profileId: profileId
        specialConsiderations:
        - specialConsiderations
        - specialConsiderations
        name: name
        designation: designation
        userType: userType
        region: region
        department: department
        email: ""
        age: age
    OrganizationCode:
      type: object
      properties:
        organization:
          type: string
        code:
          type: string
        isPrimary:
          type: string
      example:
        code: code
        isPrimary: isPrimary
        organization: organization
    UpdateUserProfileRequest:
      required:
      - name
      - profileId
      type: object
      properties:
        profileId:
          type: string
        name:
          type: string
        age:
          type: integer
        language:
          type: string
        country:
          type: string
        department:
          type: string
        designation:
          type: string
        ethnicity:
          type: string
        specialConsiderations:
          type: array
          items:
            type: string
        orgCode:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationCode'
    UpdateUserProfileResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      example:
        message: message
        status: status
    Sprint:
      type: object
      properties:
        sprintId:
          type: string
          description: The ID of the sprint
        sprintName:
          type: string
          description: The name of the sprint
        sprintStatus:
          type: string
          description: The status of the sprint
        _id:
          type: string
          description: The unique identifier of the sprint
      example:
        sprintId: sprintId
        sprintStatus: sprintStatus
        sprintName: sprintName
        _id: _id
    Quiz:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the quiz
        quizId:
          type: string
          description: The ID of the quiz
        quizNumber:
          type: string
          description: The number of the quiz
        quizName:
          type: string
          description: The name of the quiz
        totalQuestionCount:
          type: string
          description: The total number of questions in the quiz
        completedQuestionCount:
          type: string
          description: The number of completed questions in the quiz
        skippedQuestionCount:
          type: string
          description: The number of skipped questions in the quiz
        _sprintId:
          type: string
          description: The ID of the sprint associated with the quiz
      example:
        totalQuestionCount: totalQuestionCount
        quizId: quizId
        quizName: quizName
        skippedQuestionCount: skippedQuestionCount
        _id: _id
        quizNumber: quizNumber
        _sprintId: _sprintId
        completedQuestionCount: completedQuestionCount
    Question:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the question
        questionId:
          type: string
          description: The ID of the question
        questionNumber:
          type: string
          description: The number of the question
        questionText:
          type: string
          description: The text of the question
        questionContext:
          type: string
          description: The context of the question
        questionOptions:
          type: array
          description: The options for the question
          items:
            $ref: '#/components/schemas/QuestionOption'
        questionStatus:
          type: string
          description: The status of the question
        category:
          type: string
          description: The category of the question
        classification:
          type: string
          description: The classification of the question
        _quizId:
          type: string
          description: The ID of the quiz associated with the question
      example:
        questionId: questionId
        questionContext: questionContext
        questionOptions:
        - optionVal: optionVal
          optionId: optionId
          optionGrade: optionGrade
          tags: {}
        - optionVal: optionVal
          optionId: optionId
          optionGrade: optionGrade
          tags: {}
        _quizId: _quizId
        _id: _id
        category: category
        classification: classification
        questionStatus: questionStatus
        questionText: questionText
        questionNumber: questionNumber
    QuestionOption:
      type: object
      properties:
        optionId:
          type: string
          description: The ID of the option
        optionVal:
          type: string
          description: The value of the option
        optionGrade:
          type: string
          description: The grade of the option
        tags:
          type: object
          description: The tags associated with the option
      example:
        optionVal: optionVal
        optionId: optionId
        optionGrade: optionGrade
        tags: {}
    UpdateQuestionRequest:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the question to update
        _quizId:
          type: string
          description: The ID of the quiz associated with the question
        _sprintId:
          type: string
          description: The ID of the sprint associated with the question
        isLastQuestionOfQuiz:
          type: boolean
          description: Indicates if it is the last question of the quiz
        isLastQuizOfSprint:
          type: boolean
          description: Indicates if it is the last quiz of the sprint
        quizId:
          type: string
          description: The ID of the quiz
        questionId:
          type: string
          description: The ID of the question
        userId:
          type: string
          description: The ID of the user
        questionStatus:
          type: string
          description: The status of the question
        answerOptions:
          type: array
          description: The answer options for the question
          items:
            $ref: '#/components/schemas/AnswerOption'
        numberOfMoves:
          type: integer
          description: The number of moves
    AnswerOption:
      type: object
      properties:
        optionId:
          type: string
          description: The ID of the option
        optionVal:
          type: string
          description: The value of the option
        tags:
          type: object
          description: The tags associated with the option
    UpdateQuestionResponse:
      type: object
      properties:
        status:
          type: string
          description: The status of the update operation
        message:
          type: string
          description: A message describing the result of the update operation
      example:
        message: message
        status: status
    SprintResult:
      type: object
      properties:
        userId:
          type: string
          description: The ID of the user
        sprintId:
          type: string
          description: The ID of the sprint
        spiritResult:
          $ref: '#/components/schemas/QuadResult'
        purposeResult:
          $ref: '#/components/schemas/QuadResult'
        rewardsResult:
          $ref: '#/components/schemas/QuadResult'
        professionResult:
          $ref: '#/components/schemas/QuadResult'
        resultHeadPara:
          type: string
          description: The summary of the quadrant results
        _id:
          type: string
          description: The ID of the result
        resultDateTime:
          type: string
          description: The date and time of the result
        questionCount:
          type: string
          description: The number of questions in the sprint
    QuadResult:
      type: object
      properties:
        quadscore:
          type: string
          description: The score of the quadrant
        quadDisplay:
          type: string
          description: The display name of the quadrant
        blurb:
          type: string
          description: A description of the quadrant result
      example:
        quadscore: quadscore
        blurb: blurb
        quadDisplay: quadDisplay
    GetResultDetailsResponse:
      type: object
      properties:
        status:
          type: string
          description: The status of the response
        resultDetails:
          $ref: '#/components/schemas/ResultDetails'
      example:
        resultDetails:
          professionResult: null
          resultHeadPara: resultHeadPara
          sprintId: sprintId
          rewardsResult: null
          resultDateTime: resultDateTime
          spiritResult:
            quadscore: quadscore
            blurb: blurb
            quadDisplay: quadDisplay
          _id: _id
          purposeResult: null
          userId: userId
        status: status
    ResultDetails:
      type: object
      properties:
        userId:
          type: string
          description: The ID of the user
        sprintId:
          type: string
          description: The ID of the sprint
        spiritResult:
          $ref: '#/components/schemas/QuadResult'
        purposeResult:
          $ref: '#/components/schemas/QuadResult'
        rewardsResult:
          $ref: '#/components/schemas/QuadResult'
        professionResult:
          $ref: '#/components/schemas/QuadResult'
        resultHeadPara:
          type: string
          description: The summary of the quadrant results
        _id:
          type: string
          description: The ID of the result
        resultDateTime:
          type: string
          description: The date and time of the result
      example:
        professionResult: null
        resultHeadPara: resultHeadPara
        sprintId: sprintId
        rewardsResult: null
        resultDateTime: resultDateTime
        spiritResult:
          quadscore: quadscore
          blurb: blurb
          quadDisplay: quadDisplay
        _id: _id
        purposeResult: null
        userId: userId
    GetSkillResultsDatesResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: The status code of the response
        status:
          type: string
          description: The status of the response
        message:
          type: string
          description: The message associated with the response
        result:
          type: array
          items:
            $ref: '#/components/schemas/SkillResultDate'
      example:
        result:
        - resultDateTime: resultDateTime
          isRead: true
          _id: _id
          isViewable: true
        - resultDateTime: resultDateTime
          isRead: true
          _id: _id
          isViewable: true
        message: message
        statusCode: 0
        status: status
    SkillResultDate:
      type: object
      properties:
        isRead:
          type: boolean
          description: Indicates if the result is read
        _id:
          type: string
          description: The ID of the result
        resultDateTime:
          type: string
          description: The date and time of the result
        isViewable:
          type: boolean
          description: Indicates if the result is viewable
      example:
        resultDateTime: resultDateTime
        isRead: true
        _id: _id
        isViewable: true
    UpdateSkillResultViewRequest:
      required:
      - ids
      type: object
      properties:
        ids:
          type: array
          description: The IDs of the skill results to update their view status
          items:
            type: string
    UpdateSkillResultViewResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: The status code of the response
        status:
          type: string
          description: The status of the response
        message:
          type: string
          description: The message associated with the response
        result:
          $ref: '#/components/schemas/UpdateSkillResultViewResponse_result'
      example:
        result:
          upsertedId: upsertedId
          upsertedCount: 1
          acknowledged: true
          modifiedCount: 6
          matchedCount: 5
        message: message
        statusCode: 0
        status: status
    addUser_body:
      type: object
      properties:
        deviceId:
          type: string
          example: DEVICEID123456789
        deviceType:
          type: string
          example: ANDROID
        authType:
          type: string
          example: INTERNAL
        userId:
          type: string
          example: pampanasaranya@gmail.com
        email:
          type: string
          example: pampanasaranya@gmail.com
        password:
          type: string
          example: "1234567890"
        name:
          type: string
          example: Saranya
        role:
          type: string
          example: Professional
    inline_response_200:
      type: object
      properties:
        status:
          type: string
          example: SUCCESS
        jwtToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9......
        userDetails:
          $ref: '#/components/schemas/inline_response_200_userDetails'
        message:
          type: string
          example: User Id pampanasaranyaaa@gmail.com successfully added and sent
            verification link
      example:
        jwtToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9......
        message: User Id pampanasaranyaaa@gmail.com successfully added and sent verification
          link
        userDetails:
          profileDetails:
            country: ""
            userPhoto: userPhoto
            ethnicity: ""
            gender: ""
            language: English
            userId: pampanasaranyaaa@gmail.com
            accountId: 64783663a57001858ab7ec73
            orgCode:
            - code: "-1000"
              isPrimary: "yes"
              organization: MayaMaya
            - code: "-1000"
              isPrimary: "yes"
              organization: MayaMaya
            profileId: 64783663a57001858ab7ec9f
            specialConsiderations: []
            name: Saranya
            userType: Individual User
            designation: ""
            region: ""
            department: ""
            email: pampanasaranyaaa@gmail.com
            age: ""
          accountDetails:
            deviceType: ANDROID
            registrationStatus: verified
            role: Professional
            coins: ""
            completedQuizCount: ""
            userBadgeType: Beginner
            userId: pampanasaranyaaa@gmail.com
            deviceId: DEVICEID123456789
            token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.....
            accountId: 64783663a57001858ab7ec73
            subscribedPlanType: Enterprise
            authType: INTERNAL
            completedSprintCount: ""
            completedQuestionCount: ""
        status: SUCCESS
    inline_response_200_1:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        status:
          type: string
          example: SUCCESS
        message:
          type: string
          example: verified successfully
      example:
        message: verified successfully
        statusCode: 200
        status: SUCCESS
    loginUser_body:
      type: object
      properties:
        outhType:
          type: string
          example: GOOGLE
        userId:
          type: string
          example: raviteja.karri@chromiumsolutions.com
    inline_response_200_2:
      type: object
      properties:
        numberOfCompletedSprints:
          type: string
          example: "9"
        status:
          type: string
          example: SUCCESS
        userDetails:
          $ref: '#/components/schemas/inline_response_200_2_userDetails'
        jwtToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ......
      example:
        numberOfCompletedSprints: "9"
        jwtToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ......
        userDetails:
          deviceType: Android
          accountId: 628658d75d64dacdb7bb60a9
          registrationStatus: verified
          role: Professional
          coins: "306"
          subscribedPlanType: Enterprise Plan
          outhType: GOOGLE
          userBadgeType: Collaborator
          userId: raviteja.karri@chromiumsolutions.com
          deviceId: deviceId
          completedSprintCount: "9"
        status: SUCCESS
    getQuizsBySprintId_body:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the sprint
    getQuestionsByQuizId_body:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the quiz
    getSprintResult_body:
      type: object
      properties:
        userId:
          type: string
          example: raviteja.karri@chromiumsolutions.com
    UserDetailsResponse_lastResult:
      required:
      - _id
      - resultDateTime
      type: object
      properties:
        _id:
          type: string
        resultDateTime:
          type: string
          format: date-time
      example:
        resultDateTime: 2000-01-23T04:56:07.000+00:00
        _id: _id
    UpdateSkillResultViewResponse_result:
      type: object
      properties:
        acknowledged:
          type: boolean
          description: Indicates if the operation was acknowledged
        modifiedCount:
          type: integer
          description: The count of modified documents
        upsertedId:
          type: string
          description: The ID of the upserted document (if any)
          nullable: true
        upsertedCount:
          type: integer
          description: The count of upserted documents
        matchedCount:
          type: integer
          description: The count of matched documents
      example:
        upsertedId: upsertedId
        upsertedCount: 1
        acknowledged: true
        modifiedCount: 6
        matchedCount: 5
    inline_response_200_userDetails_accountDetails:
      type: object
      properties:
        registrationStatus:
          type: string
          example: verified
        userId:
          type: string
          example: pampanasaranyaaa@gmail.com
        deviceType:
          type: string
          example: ANDROID
        authType:
          type: string
          example: INTERNAL
        deviceId:
          type: string
          example: DEVICEID123456789
        role:
          type: string
          example: Professional
        coins:
          type: string
          example: ""
        subscribedPlanType:
          type: string
          example: Enterprise
        userBadgeType:
          type: string
          example: Beginner
        completedSprintCount:
          type: string
          example: ""
        completedQuizCount:
          type: string
          example: ""
        completedQuestionCount:
          type: string
          example: ""
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.....
        accountId:
          type: string
          example: 64783663a57001858ab7ec73
      example:
        deviceType: ANDROID
        registrationStatus: verified
        role: Professional
        coins: ""
        completedQuizCount: ""
        userBadgeType: Beginner
        userId: pampanasaranyaaa@gmail.com
        deviceId: DEVICEID123456789
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.....
        accountId: 64783663a57001858ab7ec73
        subscribedPlanType: Enterprise
        authType: INTERNAL
        completedSprintCount: ""
        completedQuestionCount: ""
    inline_response_200_userDetails_profileDetails_orgCode:
      type: object
      properties:
        organization:
          type: string
          example: MayaMaya
        code:
          type: string
          example: "-1000"
        isPrimary:
          type: string
          example: "yes"
      example:
        code: "-1000"
        isPrimary: "yes"
        organization: MayaMaya
    inline_response_200_userDetails_profileDetails:
      type: object
      properties:
        userId:
          type: string
          example: pampanasaranyaaa@gmail.com
        name:
          type: string
          example: Saranya
        email:
          type: string
          example: pampanasaranyaaa@gmail.com
        country:
          type: string
          example: ""
        region:
          type: string
          example: ""
        ethnicity:
          type: string
          example: ""
        age:
          type: string
          example: ""
        gender:
          type: string
          example: ""
        language:
          type: string
          example: English
        userType:
          type: string
          example: Individual User
        specialConsiderations:
          type: array
          example: []
          items:
            type: string
        userPhoto:
          type: string
        orgCode:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_userDetails_profileDetails_orgCode'
        department:
          type: string
          example: ""
        designation:
          type: string
          example: ""
        accountId:
          type: string
          example: 64783663a57001858ab7ec73
        profileId:
          type: string
          example: 64783663a57001858ab7ec9f
      example:
        country: ""
        userPhoto: userPhoto
        ethnicity: ""
        gender: ""
        language: English
        userId: pampanasaranyaaa@gmail.com
        accountId: 64783663a57001858ab7ec73
        orgCode:
        - code: "-1000"
          isPrimary: "yes"
          organization: MayaMaya
        - code: "-1000"
          isPrimary: "yes"
          organization: MayaMaya
        profileId: 64783663a57001858ab7ec9f
        specialConsiderations: []
        name: Saranya
        userType: Individual User
        designation: ""
        region: ""
        department: ""
        email: pampanasaranyaaa@gmail.com
        age: ""
    inline_response_200_userDetails:
      type: object
      properties:
        accountDetails:
          $ref: '#/components/schemas/inline_response_200_userDetails_accountDetails'
        profileDetails:
          $ref: '#/components/schemas/inline_response_200_userDetails_profileDetails'
      example:
        profileDetails:
          country: ""
          userPhoto: userPhoto
          ethnicity: ""
          gender: ""
          language: English
          userId: pampanasaranyaaa@gmail.com
          accountId: 64783663a57001858ab7ec73
          orgCode:
          - code: "-1000"
            isPrimary: "yes"
            organization: MayaMaya
          - code: "-1000"
            isPrimary: "yes"
            organization: MayaMaya
          profileId: 64783663a57001858ab7ec9f
          specialConsiderations: []
          name: Saranya
          userType: Individual User
          designation: ""
          region: ""
          department: ""
          email: pampanasaranyaaa@gmail.com
          age: ""
        accountDetails:
          deviceType: ANDROID
          registrationStatus: verified
          role: Professional
          coins: ""
          completedQuizCount: ""
          userBadgeType: Beginner
          userId: pampanasaranyaaa@gmail.com
          deviceId: DEVICEID123456789
          token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.....
          accountId: 64783663a57001858ab7ec73
          subscribedPlanType: Enterprise
          authType: INTERNAL
          completedSprintCount: ""
          completedQuestionCount: ""
    inline_response_200_2_userDetails:
      type: object
      properties:
        registrationStatus:
          type: string
          example: verified
        userId:
          type: string
          example: raviteja.karri@chromiumsolutions.com
        deviceType:
          type: string
          example: Android
        outhType:
          type: string
          example: GOOGLE
        deviceId:
          type: string
        role:
          type: string
          example: Professional
        coins:
          type: string
          example: "306"
        subscribedPlanType:
          type: string
          example: Enterprise Plan
        userBadgeType:
          type: string
          example: Collaborator
        completedSprintCount:
          type: string
          example: "9"
        accountId:
          type: string
          example: 628658d75d64dacdb7bb60a9
      example:
        deviceType: Android
        accountId: 628658d75d64dacdb7bb60a9
        registrationStatus: verified
        role: Professional
        coins: "306"
        subscribedPlanType: Enterprise Plan
        outhType: GOOGLE
        userBadgeType: Collaborator
        userId: raviteja.karri@chromiumsolutions.com
        deviceId: deviceId
        completedSprintCount: "9"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
